- name: install nginx
  hosts:  web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.packege:
      name: nginx
      state:  present
  - name: start
    ansible.builtin.service:
      name: nginx
      state:  started
      enabled:  yes