- name: play1
  hosts:  local
  conncetion: local
  tasks:
  - name: play1
    ansible.builtin.debug:
      msg:  hellow

- name: play2
  hosts:  local
  conncetion: local
  tasks:
  - name: play2
    ansible.builtin.debug:
      msg:  heloow2
