- name: loops
  hosts:  local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg:  "hello  {{  item  }}"
    loop:
    - ram
    - pavani

- name: install packages
  hosts:  web
  become: yes
  tasks:
  - name: intall
    ansible.builtin.package:
      name: "{{ item  }}"
      state:  installed
    loop:
    - mysql
    - git
    - zip